---
abstract: 'indicates the progress of a lengthy operation visually'
author:
  - 'Farhad Fouladi <farhad@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ProgressBar
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  Term::ReadKey: 0
  Test::More: 0
version: 0.1
